<a href="https://colab.research.google.com/github/JotJaw/data-science-bootcamp/blob/main/02_analiza_danych/01_pandas_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [58]:
import pandas as pd
pd.__version__

'2.2.2'

#Podstawowe struktury danych: pd.Series

In [2]:
s = pd.Series(data=[1,2,4,6])
s

0    1
1    2
2    4
3    6
dtype: int64

indeks można dowolnie zmienić

za indeks można użyć daty!

In [5]:
s = pd.Series(data=[1.,2,4,6], index=['a','b','c','d'], name ='sample') #jeden float, wszędzie float
s

a    1.0
b    2.0
c    4.0
d    6.0
Name: sample, dtype: float64

wstawianie braków danych

In [59]:
import numpy as np
np.nan

nan

brak wartości - wartość NaN nie zostanie wzięta pod uwagę przy wyliczeniach - w przeciwieństwie do np. wartości 0

In [7]:
s = pd.Series(data=[1.,np.nan,4,6], index=['a','b','c','d'], name ='sample') #jeden float, wszędzie float
s

a    1.0
b    NaN
c    4.0
d    6.0
Name: sample, dtype: float64

In [8]:
s = pd.Series(data=[True,False,False])
s

0     True
1    False
2    False
dtype: bool

In [18]:
s = pd.Series(data=np.arange(10,20), index=pd.date_range(start='20200101',periods=10)) #period - ile dni od dnia startu
s

2020-01-01    10
2020-01-02    11
2020-01-03    12
2020-01-04    13
2020-01-05    14
2020-01-06    15
2020-01-07    16
2020-01-08    17
2020-01-09    18
2020-01-10    19
Freq: D, dtype: int64

In [19]:
s.index

DatetimeIndex(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
               '2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08',
               '2020-01-09', '2020-01-10'],
              dtype='datetime64[ns]', freq='D')

In [20]:
list(s.index)

[Timestamp('2020-01-01 00:00:00'),
 Timestamp('2020-01-02 00:00:00'),
 Timestamp('2020-01-03 00:00:00'),
 Timestamp('2020-01-04 00:00:00'),
 Timestamp('2020-01-05 00:00:00'),
 Timestamp('2020-01-06 00:00:00'),
 Timestamp('2020-01-07 00:00:00'),
 Timestamp('2020-01-08 00:00:00'),
 Timestamp('2020-01-09 00:00:00'),
 Timestamp('2020-01-10 00:00:00')]

In [22]:
s = pd.Series(data=['python','java','sql'], name='languages')
s

0    python
1      java
2       sql
Name: languages, dtype: object

In [3]:
type(s)

pandas.core.series.Series

##atrybuty

###index

In [4]:
s.index

RangeIndex(start=0, stop=3, step=1)

###values

In [13]:
s.values

array(['python', 'java', 'sql'], dtype=object)

###dtypes

In [23]:
s.dtypes #O = object

dtype('O')

###shape

In [25]:
s.shape

(3,)

##Wycinanie

In [26]:
price = pd.Series(data={'Apple':200,'CD Projekt':60,'Amazon':1900,'KGHM':np.nan}) #index -> klucz ze słownika
price

Apple          200.0
CD Projekt      60.0
Amazon        1900.0
KGHM             NaN
dtype: float64

In [29]:
price['CD Projekt']

np.float64(60.0)

In [30]:
price[1]

/tmp/ipykernel_503/4074423798.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  price[1]

np.float64(60.0)

##Podstawowe funkcje

In [31]:
price.count() #ile elementów w obiekcie - zlicza tylko dane występujące

np.int64(3)

In [33]:
price.value_counts() #rozkład danych - ile razy dana wartość; użyteczna do budowy histogramu

200.0     1
60.0      1
1900.0    1
Name: count, dtype: int64

nie zlicza braku, chyba że ustawimy paramet dropna=False

In [44]:
price.value_counts(dropna=False)

200.0     1
60.0      1
1900.0    1
NaN       1
Name: count, dtype: int64

In [34]:
price.sum()

np.float64(2160.0)

In [35]:
price.max()

1900.0

In [36]:
price.min()

60.0

In [37]:
price.std()

1024.3046421841502

In [46]:
price.describe() #kwantyle rozkładu (50% = median)

count       3.000000
mean      720.000000
std      1024.304642
min        60.000000
25%       130.000000
50%       200.000000
75%      1050.000000
max      1900.000000
dtype: float64

In [49]:
price.nlargest(2) #największe 2

Amazon    1900.0
Apple      200.0
dtype: float64

In [51]:
price.nsmallest(2) #najmniejsze - jako parametr - ile

CD Projekt     60.0
Apple         200.0
dtype: float64

In [52]:
price.rank() #uporządkowanie od najniższej - przypisanie wartości

Apple         2.0
CD Projekt    1.0
Amazon        3.0
KGHM          NaN
dtype: float64

In [54]:
price.sort_values() #braki danych na końcu

CD Projekt      60.0
Apple          200.0
Amazon        1900.0
KGHM             NaN
dtype: float64

In [55]:
price.sort_values(ascending=False) #zmiana porządku sortowania

Amazon        1900.0
Apple          200.0
CD Projekt      60.0
KGHM             NaN
dtype: float64

###metoda apply()

In [63]:
price_pln = price.apply(lambda x: x * 3.8) #dane w PLN; funkcja może być osobno zdefiniowana i przekazana jako parametr; jeżeli prosta - może być zdefiniowana przy pomocy instrukcji lamda

In [61]:
price #bez zmian - nie zostały przypisane do obiektu

Apple          200.0
CD Projekt      60.0
Amazon        1900.0
KGHM             NaN
dtype: float64

In [64]:
price_pln

Apple          760.0
CD Projekt     228.0
Amazon        7220.0
KGHM             NaN
dtype: float64

#Podstawowe struktury danych: pd.DataFrame

In [65]:
df = pd.DataFrame(data=[12,12,32])
df

    0
0  12
1  12
2  32

In [66]:
df = pd.DataFrame(data=[12,12,32], index=['first','second','third'], columns=['col_1'])
df

        col_1
first      12
second     12
third      32

In [ ]:
df =