<a href="https://colab.research.google.com/github/JotJaw/data-science-bootcamp/blob/main/02_analiza_danych/01_pandas_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
pd.__version__

'2.2.2'

#Podstawowe struktury danych: pd.Series

In [ ]:
s = pd.Series(data=[1,2,4,6])
s

0    1
1    2
2    4
3    6
dtype: int64

indeks można dowolnie zmienić

za indeks można użyć daty!

In [ ]:
s = pd.Series(data=[1.,2,4,6], index=['a','b','c','d'], name ='sample') #jeden float, wszędzie float
s

a    1.0
b    2.0
c    4.0
d    6.0
Name: sample, dtype: float64

wstawianie braków danych

In [4]:
import numpy as np
np.nan

nan

brak wartości - wartość NaN nie zostanie wzięta pod uwagę przy wyliczeniach - w przeciwieństwie do np. wartości 0

In [ ]:
s = pd.Series(data=[1.,np.nan,4,6], index=['a','b','c','d'], name ='sample') #jeden float, wszędzie float
s

a    1.0
b    NaN
c    4.0
d    6.0
Name: sample, dtype: float64

In [ ]:
s = pd.Series(data=[True,False,False])
s

0     True
1    False
2    False
dtype: bool

In [ ]:
s = pd.Series(data=np.arange(10,20), index=pd.date_range(start='20200101',periods=10)) #period - ile dni od dnia startu
s

2020-01-01    10
2020-01-02    11
2020-01-03    12
2020-01-04    13
2020-01-05    14
2020-01-06    15
2020-01-07    16
2020-01-08    17
2020-01-09    18
2020-01-10    19
Freq: D, dtype: int64

In [ ]:
s.index

DatetimeIndex(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
               '2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08',
               '2020-01-09', '2020-01-10'],
              dtype='datetime64[ns]', freq='D')

In [ ]:
list(s.index)

[Timestamp('2020-01-01 00:00:00'),
 Timestamp('2020-01-02 00:00:00'),
 Timestamp('2020-01-03 00:00:00'),
 Timestamp('2020-01-04 00:00:00'),
 Timestamp('2020-01-05 00:00:00'),
 Timestamp('2020-01-06 00:00:00'),
 Timestamp('2020-01-07 00:00:00'),
 Timestamp('2020-01-08 00:00:00'),
 Timestamp('2020-01-09 00:00:00'),
 Timestamp('2020-01-10 00:00:00')]

In [ ]:
s = pd.Series(data=['python','java','sql'], name='languages')
s

0    python
1      java
2       sql
Name: languages, dtype: object

In [ ]:
type(s)

pandas.core.series.Series

##atrybuty

###index

In [ ]:
s.index

RangeIndex(start=0, stop=3, step=1)

###values

In [ ]:
s.values

array(['python', 'java', 'sql'], dtype=object)

###dtypes

In [ ]:
s.dtypes #O = object

dtype('O')

###shape

In [ ]:
s.shape

(3,)

##Wycinanie

In [ ]:
price = pd.Series(data={'Apple':200,'CD Projekt':60,'Amazon':1900,'KGHM':np.nan}) #index -> klucz ze słownika
price

Apple          200.0
CD Projekt      60.0
Amazon        1900.0
KGHM             NaN
dtype: float64

In [ ]:
price['CD Projekt']

np.float64(60.0)

In [ ]:
price[1]

/tmp/ipykernel_503/4074423798.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  price[1]

np.float64(60.0)

##Podstawowe funkcje

In [ ]:
price.count() #ile elementów w obiekcie - zlicza tylko dane występujące

np.int64(3)

In [ ]:
price.value_counts() #rozkład danych - ile razy dana wartość; użyteczna do budowy histogramu

200.0     1
60.0      1
1900.0    1
Name: count, dtype: int64

nie zlicza braku, chyba że ustawimy paramet dropna=False

In [ ]:
price.value_counts(dropna=False)

200.0     1
60.0      1
1900.0    1
NaN       1
Name: count, dtype: int64

In [ ]:
price.sum()

np.float64(2160.0)

In [ ]:
price.max()

1900.0

In [ ]:
price.min()

60.0

In [ ]:
price.std()

1024.3046421841502

In [ ]:
price.describe() #kwantyle rozkładu (50% = median)

count       3.000000
mean      720.000000
std      1024.304642
min        60.000000
25%       130.000000
50%       200.000000
75%      1050.000000
max      1900.000000
dtype: float64

In [ ]:
price.nlargest(2) #największe 2

Amazon    1900.0
Apple      200.0
dtype: float64

In [ ]:
price.nsmallest(2) #najmniejsze - jako parametr - ile

CD Projekt     60.0
Apple         200.0
dtype: float64

In [ ]:
price.rank() #uporządkowanie od najniższej - przypisanie wartości

Apple         2.0
CD Projekt    1.0
Amazon        3.0
KGHM          NaN
dtype: float64

In [ ]:
price.sort_values() #braki danych na końcu

CD Projekt      60.0
Apple          200.0
Amazon        1900.0
KGHM             NaN
dtype: float64

In [ ]:
price.sort_values(ascending=False) #zmiana porządku sortowania

Amazon        1900.0
Apple          200.0
CD Projekt      60.0
KGHM             NaN
dtype: float64

###metoda apply()

In [ ]:
price_pln = price.apply(lambda x: x * 3.8) #dane w PLN; funkcja może być osobno zdefiniowana i przekazana jako parametr; jeżeli prosta - może być zdefiniowana przy pomocy instrukcji lamda

In [ ]:
price #bez zmian - nie zostały przypisane do obiektu

Apple          200.0
CD Projekt      60.0
Amazon        1900.0
KGHM             NaN
dtype: float64

In [ ]:
price_pln

Apple          760.0
CD Projekt     228.0
Amazon        7220.0
KGHM             NaN
dtype: float64

#Podstawowe struktury danych: pd.DataFrame

In [ ]:
df = pd.DataFrame(data=[12,12,32])
df

    0
0  12
1  12
2  32

In [ ]:
df = pd.DataFrame(data=[12,12,32], index=['first','second','third'], columns=['col_1'])
df

        col_1
first      12
second     12
third      32

In [5]:
df = pd.DataFrame(data={'WIG20':['PKN ORLEN','PKO BP'],
                        'mWIG40': ['Amica', 'Playway']})
df

       WIG20   mWIG40
0  PKN ORLEN    Amica
1     PKO BP  Playway

In [6]:
df = pd.DataFrame(data=[[10,12,13],[23,12,10]], index=['first','second'], columns=['col_1','col_2','col_3'])
df

        col_1  col_2  col_3
first      10     12     13
second     23     12     10

In [7]:
df.columns

Index(['col_1', 'col_2', 'col_3'], dtype='object')

In [8]:
df.index

Index(['first', 'second'], dtype='object')

In [9]:
df.values

array([[10, 12, 13],
       [23, 12, 10]])

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2 entries, first to second
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   col_1   2 non-null      int64
 1   col_2   2 non-null      int64
 2   col_3   2 non-null      int64
dtypes: int64(3)
memory usage: 172.0+ bytes

In [11]:
df.describe()

           col_1  col_2     col_3
count   2.000000    2.0   2.00000
mean   16.500000   12.0  11.50000
std     9.192388    0.0   2.12132
min    10.000000   12.0  10.00000
25%    13.250000   12.0  10.75000
50%    16.500000   12.0  11.50000
75%    19.750000   12.0  12.25000
max    23.000000   12.0  13.00000

In [12]:
df.describe().T

       count  mean       std   min    25%   50%    75%   max
col_1    2.0  16.5  9.192388  10.0  13.25  16.5  19.75  23.0
col_2    2.0  12.0  0.000000  12.0  12.00  12.0  12.00  12.0
col_3    2.0  11.5  2.121320  10.0  10.75  11.5  12.25  13.0

##Selekcja kolumn (zmiennych) w df

In [13]:
df

        col_1  col_2  col_3
first      10     12     13
second     23     12     10

In [19]:
df['col_2'] #wyświetlany jest obiekt series -> df składa się z series; jeżeli chcemy wyciąć otrzymując df - inaczej

first     12
second    12
Name: col_2, dtype: int64

In [21]:
type(df['col_2'])

pandas.core.series.Series

In [22]:
df[['col_2']] #podwójne nawiasy kwadratowe, aby typ otrzymanego obiektu był df

        col_2
first      12
second     12

In [23]:
type(df[['col_2']])

pandas.core.frame.DataFrame

In [24]:
#zmiana nazw kolmn
df.columns = ['a','b','c']
df

         a   b   c
first   10  12  13
second  23  12  10

In [26]:
df.b #nie zawsze sposób praktyczny - np. jeżeli nazwa kolumny ze spacją

first     12
second    12
Name: b, dtype: int64

##tworzenie nowej kolumny

In [28]:
df['d']= df.a + df.c
df

         a   b   c   d
first   10  12  13  23
second  23  12  10  33

In [29]:
df = pd.DataFrame(data=[[10,12,13],[23,12,10]], index=['first','second'], columns=['col_1','col_2','col_3'])
df

        col_1  col_2  col_3
first      10     12     13
second     23     12     10

In [30]:
df.loc['first'] #pierwszy rząd

col_1    10
col_2    12
col_3    13
Name: first, dtype: int64

In [31]:
df.iloc[0] #metoda do wskazania indeksu wiersza

col_1    10
col_2    12
col_3    13
Name: first, dtype: int64

In [33]:
df.loc['first', 'col_2'] #pobieranie konkretnej komórki

np.int64(12)

In [35]:
df.loc[:,'col_2'] #pobieranie konkretnej kolumny - wszystkie wiersze, kolumna 2

first     12
second    12
Name: col_2, dtype: int64

In [36]:
df.iloc[0, 1] #indeks wiersza i kolumny

np.int64(12)