<a href="https://colab.research.google.com/github/JotJaw/data-science-bootcamp/blob/main/02_analiza_danych/02_dane_gieldowe.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

print(f'numpy version: {np.__version__}')
print(f'pandas version: {pd.__version__}')

numpy version: 2.0.2
pandas version: 2.2.2

#Załadowanie danych

In [3]:
def fetch_financial_data(company='AMZN'):
  """Pobiera dane dotyczące notowań spółek na giełdzie według symboli
  z seriwsu stooq.pl"""
  import pandas_datareader.data as web
  return web.DataReader(name=company, data_source='stooq')

df = fetch_financial_data()
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 1254 entries, 2026-03-06 to 2021-03-10
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Open    1254 non-null   float64
 1   High    1254 non-null   float64
 2   Low     1254 non-null   float64
 3   Close   1254 non-null   float64
 4   Volume  1254 non-null   int64
dtypes: float64(4), int64(1)
memory usage: 58.8 KB

In [4]:
df #jako indeks data sesji giełdowej - mogą być przerwy weekendowe;
#cena otwarcia, najwyższa, najniższa w ciągu dnia, oraz cena zamknięcia; Volume - wartość wlumenu, ile papieru obróciło się podczas danej sesji giełdowej

               Open     High      Low    Close    Volume
Date
2026-03-06  214.990  217.320  212.530  213.120  51152716
2026-03-05  215.980  220.470  215.590  218.860  60943447
2026-03-04  210.470  217.540  210.150  216.820  54731101
2026-03-03  203.100  209.178  202.480  208.630  43184918
2026-03-02  204.550  209.730  203.460  208.390  46001010
...             ...      ...      ...      ...       ...
2021-03-16  155.248  156.445  153.793  154.593  50775280
2021-03-15  153.728  154.112  151.604  154.084  58371840
2021-03-12  153.750  154.949  152.275  154.474  48437760
2021-03-11  155.200  156.589  154.146  155.680  55527820
2021-03-10  154.922  155.823  151.502  152.882  60249780

[1254 rows x 5 columns]

In [5]:
df.head() #bez prarametru - 5 pierwszych wierszy, z parametrem - tyle, ile chcemy

              Open     High     Low   Close    Volume
Date
2026-03-06  214.99  217.320  212.53  213.12  51152716
2026-03-05  215.98  220.470  215.59  218.86  60943447
2026-03-04  210.47  217.540  210.15  216.82  54731101
2026-03-03  203.10  209.178  202.48  208.63  43184918
2026-03-02  204.55  209.730  203.46  208.39  46001010

In [6]:
df.tail() #5 ostatnich

               Open     High      Low    Close    Volume
Date
2021-03-16  155.248  156.445  153.793  154.593  50775280
2021-03-15  153.728  154.112  151.604  154.084  58371840
2021-03-12  153.750  154.949  152.275  154.474  48437760
2021-03-11  155.200  156.589  154.146  155.680  55527820
2021-03-10  154.922  155.823  151.502  152.882  60249780

In [7]:
df.head(3)

              Open    High     Low   Close    Volume
Date
2026-03-06  214.99  217.32  212.53  213.12  51152716
2026-03-05  215.98  220.47  215.59  218.86  60943447
2026-03-04  210.47  217.54  210.15  216.82  54731101

In [8]:
df.tail(1)

               Open     High      Low    Close    Volume
Date
2021-03-10  154.922  155.823  151.502  152.882  60249780

In [9]:
df.columns

Index(['Open', 'High', 'Low', 'Close', 'Volume'], dtype='object')

In [12]:
df.columns = [col.lower() for col in df.columns] #zmiana nazw kolumn w df
df.head()

              open     high     low   close    volume
Date
2026-03-06  214.99  217.320  212.53  213.12  51152716
2026-03-05  215.98  220.470  215.59  218.86  60943447
2026-03-04  210.47  217.540  210.15  216.82  54731101
2026-03-03  203.10  209.178  202.48  208.63  43184918
2026-03-02  204.55  209.730  203.46  208.39  46001010

In [15]:
df.describe()

             open         high          low        close        volume
count  1254.00000  1254.000000  1254.000000  1254.000000  1.254000e+03
mean    165.69367   167.646760   163.593855   165.666167  5.681854e+07
std      42.04433    42.203706    41.744903    41.983681  2.703892e+07
min      82.80000    83.480000    81.430000    81.820000  1.142054e+07
25%     131.99750   133.600000   130.443750   131.932500  3.953774e+07
50%     167.84000   169.673000   166.230000   168.616000  5.080720e+07
75%     194.49750   196.925000   192.220000   194.357500  6.636190e+07
max     255.36000   258.600000   252.900000   254.000000  2.726617e+08

In [17]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
open,1254.0,1.656937e+02,4.204433e+01,82.80,1.319975e+02,1.678400e+02,1.944975e+02,2.553600e+02
high,1254.0,1.676468e+02,4.220371e+01,83.48,1.336000e+02,1.696730e+02,1.969250e+02,2.586000e+02
low,1254.0,1.635939e+02,4.174490e+01,81.43,1.304438e+02,1.662300e+02,1.922200e+02,2.529000e+02
close,1254.0,1.656662e+02,4.198368e+01,81.82,1.319325e+02,1.686160e+02,1.943575e+02,2.540000e+02
volume,1254.0,5.681854e+07,2.703892e+07,11420543.00,3.953774e+07,5.080720e+07,6.636190e+07,2.726617e+08