<a href="https://colab.research.google.com/github/JotJaw/data-science-bootcamp/blob/main/02_analiza_danych/03_zapis_odczyt.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:

def fetch_financial_data(company='AMZN'):
    """
    This function fetch stock market quotations.
    """
    import pandas_datareader.data as web
    return web.DataReader(name=company, data_source='stooq')

df = fetch_financial_data('META')
df.head()

              Open    High       Low    Close    Volume
Date
2026-03-09  634.78  647.75  626.7800  647.340  13489742
2026-03-06  647.90  649.47  636.1100  644.860  13159356
2026-03-05  661.93  670.70  650.3100  660.205  13341367
2026-03-04  657.96  672.77  657.6711  667.520  10810054
2026-03-03  648.29  659.04  638.8400  654.991  12263754

#Zapis/Odczyt danych z pliku CSV

In [3]:
df.to_csv('meta.csv')

In [4]:
df_nov = df[(df.index.month == 11) & (df.index.year == 2025)]
df_nov

               Open      High       Low   Close    Volume
Date
2025-11-28  636.075  648.0500  635.5000  647.95  11033198
2025-11-26  637.690  638.3600  631.6300  633.61  15209481
2025-11-25  624.000  637.0450  618.3000  636.22  25212978
2025-11-24  598.720  616.7000  597.6301  613.05  23554932
2025-11-21  588.500  598.1200  581.8600  594.25  21052624
2025-11-20  603.500  606.7200  583.3500  589.15  20603024
2025-11-19  593.715  595.3300  581.2500  590.32  24744703
2025-11-18  591.600  603.6600  583.7800  597.69  25500647
2025-11-17  609.035  611.6900  595.4000  602.01  16501331
2025-11-14  601.790  613.6800  595.2000  609.46  20724146
2025-11-13  613.070  617.6500  603.0000  609.89  20973845
2025-11-12  628.130  628.9900  607.7700  609.01  24493272
2025-11-11  628.000  629.5600  619.3900  627.08  13302187
2025-11-10  631.090  635.0000  618.1050  631.76  19245000
2025-11-07  616.485  622.1348  601.2000  621.71  29946826
2025-11-06  635.850  636.0000  618.0000  618.94  23628750
2025-11-05  632.310  642.2300  626.5375  635.95  20219855
2025-11-04  628.035  641.7399  626.0100  627.32  27356553
2025-11-03  656.000  659.3299  636.1800  637.71  33003599

In [5]:
df_nov.to_csv('meta_nov.csv')

In [6]:
new_df = pd.read_csv('meta_nov.csv')
new_df

          Date     Open      High       Low   Close    Volume
0   2025-11-28  636.075  648.0500  635.5000  647.95  11033198
1   2025-11-26  637.690  638.3600  631.6300  633.61  15209481
2   2025-11-25  624.000  637.0450  618.3000  636.22  25212978
3   2025-11-24  598.720  616.7000  597.6301  613.05  23554932
4   2025-11-21  588.500  598.1200  581.8600  594.25  21052624
5   2025-11-20  603.500  606.7200  583.3500  589.15  20603024
6   2025-11-19  593.715  595.3300  581.2500  590.32  24744703
7   2025-11-18  591.600  603.6600  583.7800  597.69  25500647
8   2025-11-17  609.035  611.6900  595.4000  602.01  16501331
9   2025-11-14  601.790  613.6800  595.2000  609.46  20724146
10  2025-11-13  613.070  617.6500  603.0000  609.89  20973845
11  2025-11-12  628.130  628.9900  607.7700  609.01  24493272
12  2025-11-11  628.000  629.5600  619.3900  627.08  13302187
13  2025-11-10  631.090  635.0000  618.1050  631.76  19245000
14  2025-11-07  616.485  622.1348  601.2000  621.71  29946826
15  2025-11-06  635.850  636.0000  618.0000  618.94  23628750
16  2025-11-05  632.310  642.2300  626.5375  635.95  20219855
17  2025-11-04  628.035  641.7399  626.0100  627.32  27356553
18  2025-11-03  656.000  659.3299  636.1800  637.71  33003599

In [8]:
df_nov.to_excel('meta_nov.xlsx')

In [9]:
new_df = pd.read_excel('meta_nov.xlsx')
new_df

         Date     Open      High       Low   Close    Volume
0  2025-11-28  636.075  648.0500  635.5000  647.95  11033198
1  2025-11-26  637.690  638.3600  631.6300  633.61  15209481
2  2025-11-25  624.000  637.0450  618.3000  636.22  25212978
3  2025-11-24  598.720  616.7000  597.6301  613.05  23554932
4  2025-11-21  588.500  598.1200  581.8600  594.25  21052624
5  2025-11-20  603.500  606.7200  583.3500  589.15  20603024
6  2025-11-19  593.715  595.3300  581.2500  590.32  24744703
7  2025-11-18  591.600  603.6600  583.7800  597.69  25500647
8  2025-11-17  609.035  611.6900  595.4000  602.01  16501331
9  2025-11-14  601.790  613.6800  595.2000  609.46  20724146
10 2025-11-13  613.070  617.6500  603.0000  609.89  20973845
11 2025-11-12  628.130  628.9900  607.7700  609.01  24493272
12 2025-11-11  628.000  629.5600  619.3900  627.08  13302187
13 2025-11-10  631.090  635.0000  618.1050  631.76  19245000
14 2025-11-07  616.485  622.1348  601.2000  621.71  29946826
15 2025-11-06  635.850  636.0000  618.0000  618.94  23628750
16 2025-11-05  632.310  642.2300  626.5375  635.95  20219855
17 2025-11-04  628.035  641.7399  626.0100  627.32  27356553
18 2025-11-03  656.000  659.3299  636.1800  637.71  33003599

In [10]:
new_df = pd.read_excel('meta_nov.xlsx', index_col=0) #która kolumna ma być indeksem
new_df

               Open      High       Low   Close    Volume
Date
2025-11-28  636.075  648.0500  635.5000  647.95  11033198
2025-11-26  637.690  638.3600  631.6300  633.61  15209481
2025-11-25  624.000  637.0450  618.3000  636.22  25212978
2025-11-24  598.720  616.7000  597.6301  613.05  23554932
2025-11-21  588.500  598.1200  581.8600  594.25  21052624
2025-11-20  603.500  606.7200  583.3500  589.15  20603024
2025-11-19  593.715  595.3300  581.2500  590.32  24744703
2025-11-18  591.600  603.6600  583.7800  597.69  25500647
2025-11-17  609.035  611.6900  595.4000  602.01  16501331
2025-11-14  601.790  613.6800  595.2000  609.46  20724146
2025-11-13  613.070  617.6500  603.0000  609.89  20973845
2025-11-12  628.130  628.9900  607.7700  609.01  24493272
2025-11-11  628.000  629.5600  619.3900  627.08  13302187
2025-11-10  631.090  635.0000  618.1050  631.76  19245000
2025-11-07  616.485  622.1348  601.2000  621.71  29946826
2025-11-06  635.850  636.0000  618.0000  618.94  23628750
2025-11-05  632.310  642.2300  626.5375  635.95  20219855
2025-11-04  628.035  641.7399  626.0100  627.32  27356553
2025-11-03  656.000  659.3299  636.1800  637.71  33003599

#London Bike DataSet

In [21]:
df = pd.read_csv('london_bike.csv')
df

,timestamp,cnt,t1,t2,hum,wind_speed,weather_code,is_holiday,is_weekend,season
0,2015-01-04 00:00:00,182,3.0,2.0,93.0,6.0,3.0,0.0,1.0,3.0
1,2015-01-04 01:00:00,138,3.0,2.5,93.0,5.0,1.0,0.0,1.0,3.0
2,2015-01-04 02:00:00,134,2.5,2.5,96.5,0.0,1.0,0.0,1.0,3.0
3,2015-01-04 03:00:00,72,2.0,2.0,100.0,0.0,1.0,0.0,1.0,3.0
4,2015-01-04 04:00:00,47,2.0,0.0,93.0,6.5,1.0,0.0,1.0,3.0
...,...,...,...,...,...,...,...,...,...,...
17409,2017-01-03 19:00:00,1042,5.0,1.0,81.0,19.0,3.0,0.0,0.0,3.0
17410,2017-01-03 20:00:00,541,5.0,1.0,81.0,21.0,4.0,0.0,0.0,3.0
17411,2017-01-03 21:00:00,337,5.5,1.5,78.5,24.0,4.0,0.0,0.0,3.0
17412,2017-01-03 22:00:00,224,5.5,1.5,76.0,23.0,4.0,0.0,0.0,3.0
17413,2017-01-03 23:00:00,139,5.0,1.0,76.0,22.0,2.0,0.0,0.0,3.0

In [18]:
df.head()

,cnt,t1,t2,hum,wind_speed,weather_code,is_holiday,is_weekend,season
timestamp,,,,,,,,,
2015-01-04 00:00:00,182,3.0,2.0,93.0,6.0,3.0,0.0,1.0,3.0
2015-01-04 01:00:00,138,3.0,2.5,93.0,5.0,1.0,0.0,1.0,3.0
2015-01-04 02:00:00,134,2.5,2.5,96.5,0.0,1.0,0.0,1.0,3.0
2015-01-04 03:00:00,72,2.0,2.0,100.0,0.0,1.0,0.0,1.0,3.0
2015-01-04 04:00:00,47,2.0,0.0,93.0,6.5,1.0,0.0,1.0,3.0

In [22]:
df = df.set_index('timestamp')
df.head()

,cnt,t1,t2,hum,wind_speed,weather_code,is_holiday,is_weekend,season
timestamp,,,,,,,,,
2015-01-04 00:00:00,182,3.0,2.0,93.0,6.0,3.0,0.0,1.0,3.0
2015-01-04 01:00:00,138,3.0,2.5,93.0,5.0,1.0,0.0,1.0,3.0
2015-01-04 02:00:00,134,2.5,2.5,96.5,0.0,1.0,0.0,1.0,3.0
2015-01-04 03:00:00,72,2.0,2.0,100.0,0.0,1.0,0.0,1.0,3.0
2015-01-04 04:00:00,47,2.0,0.0,93.0,6.5,1.0,0.0,1.0,3.0

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17414 entries, 0 to 17413
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   timestamp     17414 non-null  object
 1   cnt           17414 non-null  int64
 2   t1            17414 non-null  float64
 3   t2            17414 non-null  float64
 4   hum           17414 non-null  float64
 5   wind_speed    17414 non-null  float64
 6   weather_code  17414 non-null  float64
 7   is_holiday    17414 non-null  float64
 8   is_weekend    17414 non-null  float64
 9   season        17414 non-null  float64
dtypes: float64(8), int64(1), object(1)
memory usage: 1.3+ MB