<a href="https://colab.research.google.com/github/JotJaw/data-science-bootcamp/blob/main/02_analiza_danych/04_laczenie_danych.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
pd.__version__

'2.2.2'

#Wczytanie danych

In [2]:
def fetch_financial_data(company='AMZN'):
    """
    This function fetch stock market quotations.
    """
    import pandas_datareader.data as web
    return web.DataReader(name=company, data_source='stooq')

apple = fetch_financial_data('AAPL')
amazon = fetch_financial_data('AMZN')
google = fetch_financial_data('GOOGL')
uber = fetch_financial_data('UBER')

In [25]:
uber.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 1254 entries, 2026-03-09 to 2021-03-11
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Open    1254 non-null   float64
 1   High    1254 non-null   float64
 2   Low     1254 non-null   float64
 3   Close   1254 non-null   float64
 4   Volume  1254 non-null   int64
dtypes: float64(4), int64(1)
memory usage: 58.8 KB

In [26]:
tesla = fetch_financial_data('TSLA')

In [27]:
tesla.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 1254 entries, 2026-03-09 to 2021-03-11
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Open    1254 non-null   float64
 1   High    1254 non-null   float64
 2   Low     1254 non-null   float64
 3   Close   1254 non-null   float64
 4   Volume  1254 non-null   int64
dtypes: float64(4), int64(1)
memory usage: 58.8 KB

In [31]:
inpost = fetch_financial_data('INPTS')
inpost.info()

<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Empty DataFrame

In [32]:
apple.head()

              Open     High       Low   Close    Volume
Date
2026-03-09  255.69  261.150  253.6805  259.89  38218533
2026-03-06  258.63  258.770  254.3700  257.46  41120042
2026-03-05  260.79  261.555  257.2500  260.25  49658626
2026-03-04  264.65  266.150  261.4200  262.45  39803119
2026-03-03  263.48  265.560  260.1300  263.69  38568921

#Preprocssing

In [34]:
apple.columns = ['apple_' + col.lower() for col in apple.columns]
amazon.columns = ['amazon_' + col.lower() for col in amazon.columns]
google.columns = ['google_' + col.lower() for col in google.columns]
uber.columns = ['uber_' + col.lower() for col in uber.columns]

#Konkatenacja danych

In [36]:
df = pd.concat(objs=[apple, amazon, google, uber], axis=1) #według osi 1, jeżeli jakichś danych brakuje - uzupełnione przez NaN

In [39]:
pd.set_option('display.float_format', lambda x: f'{x:.2f}')
df.describe().T

,count,mean,std,min,25%,50%,75%,max
apple_apple_open,1254.00,184.28,41.66,116.55,148.42,174.80,217.69,286.20
apple_apple_high,1254.00,186.27,41.96,117.39,150.96,176.72,220.20,288.62
apple_apple_low,1254.00,182.48,41.32,115.88,147.09,173.30,215.50,283.30
apple_apple_close,1254.00,184.46,41.65,116.90,148.84,175.15,217.48,286.19
apple_apple_volume,1254.00,68502177.72,29221279.79,17910574.00,47771688.00,61485253.00,82181850.00,320473399.00
amazon_amazon_open,1254.00,165.74,42.06,82.80,132.00,167.86,194.66,255.36
amazon_amazon_high,1254.00,167.69,42.22,83.48,133.60,169.75,197.25,258.60
amazon_amazon_low,1254.00,163.64,41.76,81.43,130.44,166.31,192.29,252.90
amazon_amazon_close,1254.00,165.71,42.00,81.82,131.93,168.63,194.53,254.00
amazon_amazon_volume,1254.00,56814067.66,27038818.51,11420543.00,39537736.50,50807204.50,66361904.00,272661720.00
google_google_open,1254.00,154.08,55.07,85.09,118.20,138.98,170.75,347.34
google_google_high,1254.00,155.88,55.71,86.21,119.32,140.67,173.21,349.00
google_google_low,1254.00,152.35,54.32,83.04,117.20,137.98,168.60,337.47
google_google_close,1254.00,154.17,55.09,83.13,118.13,139.28,170.92,343.69
google_google_volume,1254.00,32336180.83,13634100.73,9736609.00,23622417.00,29121560.00,36653970.75,127747554.00
uber_uber_open,1254.00,55.85,21.88,20.37,36.64,50.94,73.68,100.13
uber_uber_high,1254.00,56.77,22.08,21.13,37.59,51.63,74.81,101.99
uber_uber_low,1254.00,54.90,21.62,19.89,35.59,50.23,72.53,98.58
uber_uber_close,1254.00,55.84,21.85,20.46,36.71,50.81,73.82,100.10
uber_uber_volume,1254.00,23435543.65,16089371.26,4310663.00,15402153.25,19832038.50,27304259.00,364261230.00

In [40]:
df.corr() #współczynniki korelacji poszczególnych zmiennych

,apple_apple_open,apple_apple_high,apple_apple_low,apple_apple_close,apple_apple_volume,amazon_amazon_open,amazon_amazon_high,amazon_amazon_low,amazon_amazon_close,amazon_amazon_volume,google_google_open,google_google_high,google_google_low,google_google_close,google_google_volume,uber_uber_open,uber_uber_high,uber_uber_low,uber_uber_close,uber_uber_volume
apple_apple_open,1.00,1.00,1.00,1.00,-0.47,0.76,0.76,0.76,0.76,-0.40,0.87,0.87,0.87,0.87,0.00,0.78,0.78,0.78,0.78,-0.12
apple_apple_high,1.00,1.00,1.00,1.00,-0.46,0.76,0.76,0.76,0.76,-0.39,0.87,0.87,0.87,0.87,0.01,0.78,0.78,0.78,0.78,-0.11
apple_apple_low,1.00,1.00,1.00,1.00,-0.48,0.76,0.76,0.76,0.76,-0.41,0.87,0.87,0.87,0.87,-0.00,0.78,0.78,0.78,0.78,-0.12
apple_apple_close,1.00,1.00,1.00,1.00,-0.47,0.76,0.76,0.76,0.76,-0.40,0.87,0.87,0.87,0.87,0.00,0.78,0.78,0.78,0.78,-0.12
apple_apple_volume,-0.47,-0.46,-0.48,-0.47,1.00,-0.29,-0.28,-0.29,-0.29,0.57,-0.34,-0.34,-0.34,-0.34,0.27,-0.41,-0.41,-0.42,-0.41,0.24
amazon_amazon_open,0.76,0.76,0.76,0.76,-0.29,1.00,1.00,1.00,1.00,-0.39,0.82,0.81,0.82,0.82,-0.04,0.87,0.87,0.87,0.87,-0.13
amazon_amazon_high,0.76,0.76,0.76,0.76,-0.28,1.00,1.00,1.00,1.00,-0.38,0.82,0.82,0.82,0.82,-0.03,0.87,0.87,0.87,0.87,-0.13
amazon_amazon_low,0.76,0.76,0.76,0.76,-0.29,1.00,1.00,1.00,1.00,-0.40,0.81,0.81,0.82,0.81,-0.05,0.87,0.87,0.87,0.87,-0.14
amazon_amazon_close,0.76,0.76,0.76,0.76,-0.29,1.00,1.00,1.00,1.00,-0.39,0.82,0.81,0.82,0.82,-0.04,0.87,0.87,0.87,0.87,-0.13
amazon_amazon_volume,-0.40,-0.39,-0.41,-0.40,0.57,-0.39,-0.38,-0.40,-0.39,1.00,-0.30,-0.30,-0.30,-0.30,0.38,-0.45,-0.44,-0.45,-0.45,0.28
google_google_open,0.87,0.87,0.87,0.87,-0.34,0.82,0.82,0.81,0.82,-0.30,1.00,1.00,1.00,1.00,0.03,0.74,0.74,0.74,0.74,-0.12
google_google_high,0.87,0.87,0.87,0.87,-0.34,0.81,0.82,0.81,0.81,-0.30,1.00,1.00,1.00,1.00,0.04,0.74,0.74,0.74,0.74,-0.11
google_google_low,0.87,0.87,0.87,0.87,-0.34,0.82,0.82,0.82,0.82,-0.30,1.00,1.00,1.00,1.00,0.02,0.75,0.75,0.75,0.75,-0.12
google_google_close,0.87,0.87,0.87,0.87,-0.34,0.82,0.82,0.81,0.82,-0.30,1.00,1.00,1.00,1.00,0.03,0.74,0.75,0.74,0.74,-0.12
google_google_volume,0.00,0.01,-0.00,0.00,0.27,-0.04,-0.03,-0.05,-0.04,0.38,0.03,0.04,0.02,0.03,1.00,-0.01,-0.01,-0.02,-0.01,0.20
uber_uber_open,0.78,0.78,0.78,0.78,-0.41,0.87,0.87,0.87,0.87,-0.45,0.74,0.74,0.75,0.74,-0.01,1.00,1.00,1.00,1.00,-0.21
uber_uber_high,0.78,0.78,0.78,0.78,-0.41,0.87,0.87,0.87,0.87,-0.44,0.74,0.74,0.75,0.75,-0.01,1.00,1.00,1.00,1.00,-0.20
uber_uber_low,0.78,0.78,0.78,0.78,-0.42,0.87,0.87,0.87,0.87,-0.45,0.74,0.74,0.75,0.74,-0.02,1.00,1.00,1.00,1.00,-0.22
uber_uber_close,0.78,0.78,0.78,0.78,-0.41,0.87,0.87,0.87,0.87,-0.45,0.74,0.74,0.75,0.74,-0.01,1.00,1.00,1.00,1.00,-0.21
uber_uber_volume,-0.12,-0.11,-0.12,-0.12,0.24,-0.13,-0.13,-0.14,-0.13,0.28,-0.12,-0.11,-0.12,-0.12,0.20,-0.21,-0.20,-0.22,-0.21,1.00

In [41]:
df.columns #wyświetlenie wszystkich kolumn

Index(['apple_apple_open', 'apple_apple_high', 'apple_apple_low',
       'apple_apple_close', 'apple_apple_volume', 'amazon_amazon_open',
       'amazon_amazon_high', 'amazon_amazon_low', 'amazon_amazon_close',
       'amazon_amazon_volume', 'google_google_open', 'google_google_high',
       'google_google_low', 'google_google_close', 'google_google_volume',
       'uber_uber_open', 'uber_uber_high', 'uber_uber_low', 'uber_uber_close',
       'uber_uber_volume'],
      dtype='object')

In [ ]:
#chcemy współczynnik korelacji, ale tylko dla kolumn close

In [42]:
closes = [col for col in df.columns if col.endswith('close')]
closes

['apple_apple_close',
 'amazon_amazon_close',
 'google_google_close',
 'uber_uber_close']

In [43]:
df[closes]

,apple_apple_close,amazon_amazon_close,google_google_close,uber_uber_close
Date,,,,
2026-03-09,259.89,213.42,306.34,73.84
2026-03-06,257.46,213.12,298.48,75.13
2026-03-05,260.25,218.86,300.85,75.44
2026-03-04,262.45,216.82,303.03,76.65
2026-03-03,263.69,208.63,303.53,76.36
...,...,...,...,...
2021-03-17,121.63,156.79,103.73,56.36
2021-03-16,122.42,154.59,103.82,58.85
2021-03-15,120.87,154.08,102.35,60.19
2021-03-12,117.98,154.47,102.13,60.35
2021-03-11,118.90,155.68,104.65,58.95

In [44]:
df[closes].corr()

,apple_apple_close,amazon_amazon_close,google_google_close,uber_uber_close
apple_apple_close,1.00,0.76,0.87,0.78
amazon_amazon_close,0.76,1.00,0.82,0.87
google_google_close,0.87,0.82,1.00,0.74
uber_uber_close,0.78,0.87,0.74,1.00

In [45]:
#dodatkowo chcemy wolumen obrotu
closes = [col for col in df.columns if col.endswith('close') or col.endswith('volume')]
closes

['apple_apple_close',
 'apple_apple_volume',
 'amazon_amazon_close',
 'amazon_amazon_volume',
 'google_google_close',
 'google_google_volume',
 'uber_uber_close',
 'uber_uber_volume']

In [46]:
df[closes].corr()

,apple_apple_close,apple_apple_volume,amazon_amazon_close,amazon_amazon_volume,google_google_close,google_google_volume,uber_uber_close,uber_uber_volume
apple_apple_close,1.00,-0.47,0.76,-0.40,0.87,0.00,0.78,-0.12
apple_apple_volume,-0.47,1.00,-0.29,0.57,-0.34,0.27,-0.41,0.24
amazon_amazon_close,0.76,-0.29,1.00,-0.39,0.82,-0.04,0.87,-0.13
amazon_amazon_volume,-0.40,0.57,-0.39,1.00,-0.30,0.38,-0.45,0.28
google_google_close,0.87,-0.34,0.82,-0.30,1.00,0.03,0.74,-0.12
google_google_volume,0.00,0.27,-0.04,0.38,0.03,1.00,-0.01,0.20
uber_uber_close,0.78,-0.41,0.87,-0.45,0.74,-0.01,1.00,-0.21
uber_uber_volume,-0.12,0.24,-0.13,0.28,-0.12,0.20,-0.21,1.00

#Metoda append() - no longer available in this version of pansas -> you should use pd.concat()

In [47]:
uber.head()

,uber_uber_open,uber_uber_high,uber_uber_low,uber_uber_close,uber_uber_volume
Date,,,,,
2026-03-09,74.17,74.54,71.94,73.84,21208861
2026-03-06,74.73,75.57,74.19,75.13,14771234
2026-03-05,76.59,78.25,75.14,75.44,17893964
2026-03-04,75.87,77.04,75.01,76.65,19818516
2026-03-03,74.50,77.31,74.02,76.36,21892515

In [48]:
uber_6 = uber[(uber.index.month == 6) & (uber.index.year == 2025)]
uber_6

,uber_uber_open,uber_uber_high,uber_uber_low,uber_uber_close,uber_uber_volume
Date,,,,,
2025-06-30,91.69,93.39,91.52,93.30,16155270
2025-06-27,91.86,92.51,89.97,91.53,24731168
2025-06-26,91.30,94.38,90.88,93.12,23657765
2025-06-25,91.56,92.89,90.60,90.90,17400840
2025-06-24,87.99,92.48,87.91,91.65,38925080
2025-06-23,83.03,85.25,82.47,85.24,18407481
2025-06-20,84.47,85.37,83.62,83.78,27472093
2025-06-18,85.16,86.48,82.31,83.44,25976728
2025-06-17,84.57,85.48,84.24,84.76,13677826
2025-06-16,84.85,86.02,84.71,85.12,12254177
2025-06-13,84.81,85.57,83.38,83.93,18003031
2025-06-12,86.11,86.79,84.87,85.62,18776059
2025-06-11,87.59,87.60,85.94,86.58,15364234
2025-06-10,88.29,88.38,85.60,86.39,24494761
2025-06-09,86.21,87.86,86.20,87.12,22780754
2025-06-06,85.44,86.69,85.03,85.60,28172652
2025-06-05,83.62,85.75,83.08,84.67,33343311
2025-06-04,83.20,84.71,82.99,83.45,20080520
2025-06-03,83.58,83.79,81.86,82.53,25668362
2025-06-02,84.48,84.76,82.64,83.64,17047042

In [49]:
uber_7 = uber[(uber.index.month == 6) & (uber.index.year == 2025)]
uber_7

,uber_uber_open,uber_uber_high,uber_uber_low,uber_uber_close,uber_uber_volume
Date,,,,,
2025-06-30,91.69,93.39,91.52,93.30,16155270
2025-06-27,91.86,92.51,89.97,91.53,24731168
2025-06-26,91.30,94.38,90.88,93.12,23657765
2025-06-25,91.56,92.89,90.60,90.90,17400840
2025-06-24,87.99,92.48,87.91,91.65,38925080
2025-06-23,83.03,85.25,82.47,85.24,18407481
2025-06-20,84.47,85.37,83.62,83.78,27472093
2025-06-18,85.16,86.48,82.31,83.44,25976728
2025-06-17,84.57,85.48,84.24,84.76,13677826
2025-06-16,84.85,86.02,84.71,85.12,12254177
2025-06-13,84.81,85.57,83.38,83.93,18003031
2025-06-12,86.11,86.79,84.87,85.62,18776059
2025-06-11,87.59,87.60,85.94,86.58,15364234
2025-06-10,88.29,88.38,85.60,86.39,24494761
2025-06-09,86.21,87.86,86.20,87.12,22780754
2025-06-06,85.44,86.69,85.03,85.60,28172652
2025-06-05,83.62,85.75,83.08,84.67,33343311
2025-06-04,83.20,84.71,82.99,83.45,20080520
2025-06-03,83.58,83.79,81.86,82.53,25668362
2025-06-02,84.48,84.76,82.64,83.64,17047042

In [51]:
pd.concat([uber_6, uber_7])

,uber_uber_open,uber_uber_high,uber_uber_low,uber_uber_close,uber_uber_volume
Date,,,,,
2025-06-30,91.69,93.39,91.52,93.30,16155270
2025-06-27,91.86,92.51,89.97,91.53,24731168
2025-06-26,91.30,94.38,90.88,93.12,23657765
2025-06-25,91.56,92.89,90.60,90.90,17400840
2025-06-24,87.99,92.48,87.91,91.65,38925080
2025-06-23,83.03,85.25,82.47,85.24,18407481
2025-06-20,84.47,85.37,83.62,83.78,27472093
2025-06-18,85.16,86.48,82.31,83.44,25976728
2025-06-17,84.57,85.48,84.24,84.76,13677826
2025-06-16,84.85,86.02,84.71,85.12,12254177
2025-06-13,84.81,85.57,83.38,83.93,18003031
2025-06-12,86.11,86.79,84.87,85.62,18776059
2025-06-11,87.59,87.60,85.94,86.58,15364234
2025-06-10,88.29,88.38,85.60,86.39,24494761
2025-06-09,86.21,87.86,86.20,87.12,22780754
2025-06-06,85.44,86.69,85.03,85.60,28172652
2025-06-05,83.62,85.75,83.08,84.67,33343311
2025-06-04,83.20,84.71,82.99,83.45,20080520
2025-06-03,83.58,83.79,81.86,82.53,25668362
2025-06-02,84.48,84.76,82.64,83.64,17047042
2025-06-30,91.69,93.39,91.52,93.30,16155270
2025-06-27,91.86,92.51,89.97,91.53,24731168
2025-06-26,91.30,94.38,90.88,93.12,23657765
2025-06-25,91.56,92.89,90.60,90.90,17400840
2025-06-24,87.99,92.48,87.91,91.65,38925080
2025-06-23,83.03,85.25,82.47,85.24,18407481
2025-06-20,84.47,85.37,83.62,83.78,27472093
2025-06-18,85.16,86.48,82.31,83.44,25976728
2025-06-17,84.57,85.48,84.24,84.76,13677826
2025-06-16,84.85,86.02,84.71,85.12,12254177
2025-06-13,84.81,85.57,83.38,83.93,18003031
2025-06-12,86.11,86.79,84.87,85.62,18776059
2025-06-11,87.59,87.60,85.94,86.58,15364234
2025-06-10,88.29,88.38,85.60,86.39,24494761
2025-06-09,86.21,87.86,86.20,87.12,22780754
2025-06-06,85.44,86.69,85.03,85.60,28172652
2025-06-05,83.62,85.75,83.08,84.67,33343311
2025-06-04,83.20,84.71,82.99,83.45,20080520
2025-06-03,83.58,83.79,81.86,82.53,25668362
2025-06-02,84.48,84.76,82.64,83.64,17047042