<a href="https://colab.research.google.com/github/JotJaw/data-science-bootcamp/blob/main/02_analiza_danych/06_sql_porownanie.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **SQL**

---
###Spis treści:
1. [Import bibliotek](#a1)
2. [Wczytanie danych i preprocessing](#a2)
3. [Porównanie do języka SQL](#a3)

### <a name='a1'></a> Import bibliotek

In [1]:

import numpy as np
import pandas as pd
pd.__version__

'2.2.2'

### <a name='a2'></a>Wczytanie danych i preprocessing

In [2]:
url = ('https://storage.googleapis.com/esmartdata-courses-files/ds-bootcamp/online_retail.xlsx')
retail_raw = pd.read_excel(url)
retail_raw.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [3]:
retail = retail_raw.copy()
retail.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  datetime64[ns]
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 33.1+ MB

In [4]:
retail.describe()

,Quantity,InvoiceDate,UnitPrice,CustomerID
count,541909.000000,541909,541909.000000,406829.000000
mean,9.552250,2011-07-04 13:34:57.156386048,4.611114,15287.690570
min,-80995.000000,2010-12-01 08:26:00,-11062.060000,12346.000000
25%,1.000000,2011-03-28 11:34:00,1.250000,13953.000000
50%,3.000000,2011-07-19 17:17:00,2.080000,15152.000000
75%,10.000000,2011-10-19 11:27:00,4.130000,16791.000000
max,80995.000000,2011-12-09 12:50:00,38970.000000,18287.000000
std,218.081158,NaN,96.759853,1713.600303

In [6]:
retail.isnull().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [7]:
retail = retail.dropna()
retail.isnull().sum()

InvoiceNo      0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
UnitPrice      0
CustomerID     0
Country        0
dtype: int64

In [10]:
retail = retail[retail.Quantity >= 0] #nadpisanie częścią rekordów
retail.info()

<class 'pandas.core.frame.DataFrame'>
Index: 397924 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    397924 non-null  object
 1   StockCode    397924 non-null  object
 2   Description  397924 non-null  object
 3   Quantity     397924 non-null  int64
 4   InvoiceDate  397924 non-null  datetime64[ns]
 5   UnitPrice    397924 non-null  float64
 6   CustomerID   397924 non-null  float64
 7   Country      397924 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 27.3+ MB

In [11]:
retail.CustomerID = retail.CustomerID.apply(lambda x: str(int(x))) #zmiana typu kolumny z float na string z inta
retail.info()

<class 'pandas.core.frame.DataFrame'>
Index: 397924 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    397924 non-null  object
 1   StockCode    397924 non-null  object
 2   Description  397924 non-null  object
 3   Quantity     397924 non-null  int64
 4   InvoiceDate  397924 non-null  datetime64[ns]
 5   UnitPrice    397924 non-null  float64
 6   CustomerID   397924 non-null  object
 7   Country      397924 non-null  object
dtypes: datetime64[ns](1), float64(1), int64(1), object(5)
memory usage: 27.3+ MB

In [12]:
retail.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom

### <a name='a3'></a>Porównanie do języka SQL

In [13]:
# select * from retail
retail

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom
...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680,France

In [14]:
# select Quantity, UnitPrice, CustomerId from retail
retail[['Quantity', 'UnitPrice', 'CustomerID']]

        Quantity  UnitPrice CustomerID
0              6       2.55      17850
1              6       3.39      17850
2              8       2.75      17850
3              6       3.39      17850
4              6       3.39      17850
...          ...        ...        ...
541904        12       0.85      12680
541905         6       2.10      12680
541906         4       4.15      12680
541907         4       4.15      12680
541908         3       4.95      12680

[397924 rows x 3 columns]

In [15]:
# SELECT Quantity, UnitPrice, CustomerID FROM retail LIMIT 10; /*10 pierwszych wierszy*/
retail[['Quantity', 'UnitPrice', 'CustomerID']].head(10)

   Quantity  UnitPrice CustomerID
0         6       2.55      17850
1         6       3.39      17850
2         8       2.75      17850
3         6       3.39      17850
4         6       3.39      17850
5         2       7.65      17850
6         6       4.25      17850
7         6       1.85      17850
8         6       1.85      17850
9        32       1.69      13047

In [17]:
retail[['Quantity', 'UnitPrice', 'CustomerID']][:10]

   Quantity  UnitPrice CustomerID
0         6       2.55      17850
1         6       3.39      17850
2         8       2.75      17850
3         6       3.39      17850
4         6       3.39      17850
5         2       7.65      17850
6         6       4.25      17850
7         6       1.85      17850
8         6       1.85      17850
9        32       1.69      13047

In [18]:
# SELECT * FROM retial WHERE CustomerID='17850';
retail.CustomerID == '17850'

0          True
1          True
2          True
3          True
4          True
          ...
541904    False
541905    False
541906    False
541907    False
541908    False
Name: CustomerID, Length: 397924, dtype: bool

In [19]:
retail[retail.CustomerID == '17850'] #wykorzystujemy maskowanie logiczne

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom
...,...,...,...,...,...,...,...,...
4540,536790,22752,SET 7 BABUSHKA NESTING BOXES,4,2010-12-02 15:26:00,7.65,17850,United Kingdom
4541,536790,22803,IVORY EMBROIDERED QUILT,3,2010-12-02 15:26:00,35.75,17850,United Kingdom
4542,536790,21730,GLASS STAR FROSTED T-LIGHT HOLDER,12,2010-12-02 15:26:00,4.25,17850,United Kingdom
4543,536791,22632,HAND WARMER RED POLKA DOT,12,2010-12-02 15:27:00,1.85,17850,United Kingdom
4544,536791,22633,HAND WARMER UNION JACK,12,2010-12-02 15:27:00,1.85,17850,United Kingdom

In [22]:
retail.query('CustomerID == "17850"') #metoda query

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom
...,...,...,...,...,...,...,...,...
4540,536790,22752,SET 7 BABUSHKA NESTING BOXES,4,2010-12-02 15:26:00,7.65,17850,United Kingdom
4541,536790,22803,IVORY EMBROIDERED QUILT,3,2010-12-02 15:26:00,35.75,17850,United Kingdom
4542,536790,21730,GLASS STAR FROSTED T-LIGHT HOLDER,12,2010-12-02 15:26:00,4.25,17850,United Kingdom
4543,536791,22632,HAND WARMER RED POLKA DOT,12,2010-12-02 15:27:00,1.85,17850,United Kingdom
4544,536791,22633,HAND WARMER UNION JACK,12,2010-12-02 15:27:00,1.85,17850,United Kingdom

In [23]:
retail.query("CustomerID == '17850'") #metoda query; może być też tak - najpierw podwójny cudzysłów, potem ciapki

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom
...,...,...,...,...,...,...,...,...
4540,536790,22752,SET 7 BABUSHKA NESTING BOXES,4,2010-12-02 15:26:00,7.65,17850,United Kingdom
4541,536790,22803,IVORY EMBROIDERED QUILT,3,2010-12-02 15:26:00,35.75,17850,United Kingdom
4542,536790,21730,GLASS STAR FROSTED T-LIGHT HOLDER,12,2010-12-02 15:26:00,4.25,17850,United Kingdom
4543,536791,22632,HAND WARMER RED POLKA DOT,12,2010-12-02 15:27:00,1.85,17850,United Kingdom
4544,536791,22633,HAND WARMER UNION JACK,12,2010-12-02 15:27:00,1.85,17850,United Kingdom

In [24]:
# SELECT * FROM retial WHERE CustomerID='17850' and UnitPrice > 5;
retail[(retail.CustomerID == '17850') & (retail.UnitPrice > 5)]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
5,536365,22752,SET 7 BABUSHKA NESTING BOXES,2,2010-12-01 08:26:00,7.65,17850,United Kingdom
58,536373,82486,WOOD S/3 CABINET ANT WHITE FINISH,4,2010-12-01 09:02:00,6.95,17850,United Kingdom
63,536373,22752,SET 7 BABUSHKA NESTING BOXES,2,2010-12-01 09:02:00,7.65,17850,United Kingdom
75,536375,82486,WOOD S/3 CABINET ANT WHITE FINISH,4,2010-12-01 09:32:00,6.95,17850,United Kingdom
80,536375,22752,SET 7 BABUSHKA NESTING BOXES,2,2010-12-01 09:32:00,7.65,17850,United Kingdom
288,536396,82486,WOOD S/3 CABINET ANT WHITE FINISH,4,2010-12-01 10:51:00,6.95,17850,United Kingdom
293,536396,22752,SET 7 BABUSHKA NESTING BOXES,2,2010-12-01 10:51:00,7.65,17850,United Kingdom
294,536396,22803,IVORY EMBROIDERED QUILT,2,2010-12-01 10:51:00,35.75,17850,United Kingdom
425,536406,82486,WOOD S/3 CABINET ANT WHITE FINISH,4,2010-12-01 11:33:00,6.95,17850,United Kingdom
430,536406,22752,SET 7 BABUSHKA NESTING BOXES,2,2010-12-01 11:33:00,7.65,17850,United Kingdom
431,536406,22803,IVORY EMBROIDERED QUILT,2,2010-12-01 11:33:00,35.75,17850,United Kingdom
3121,536600,82486,WOOD S/3 CABINET ANT WHITE FINISH,2,2010-12-02 08:32:00,6.95,17850,United Kingdom
3127,536600,22752,SET 7 BABUSHKA NESTING BOXES,2,2010-12-02 08:32:00,7.65,17850,United Kingdom
3128,536600,22803,IVORY EMBROIDERED QUILT,2,2010-12-02 08:32:00,35.75,17850,United Kingdom
3141,536602,22752,SET 7 BABUSHKA NESTING BOXES,2,2010-12-02 08:34:00,7.65,17850,United Kingdom
3200,536609,82486,WOOD S/3 CABINET ANT WHITE FINISH,4,2010-12-02 09:41:00,6.95,17850,United Kingdom
3206,536609,22752,SET 7 BABUSHKA NESTING BOXES,2,2010-12-02 09:41:00,7.65,17850,United Kingdom
3232,536612,82486,WOOD S/3 CABINET ANT WHITE FINISH,2,2010-12-02 09:44:00,6.95,17850,United Kingdom
3433,536628,82486,WOOD S/3 CABINET ANT WHITE FINISH,2,2010-12-02 10:54:00,6.95,17850,United Kingdom
3439,536628,22752,SET 7 BABUSHKA NESTING BOXES,2,2010-12-02 10:54:00,7.65,17850,United Kingdom
3451,536630,82486,WOOD S/3 CABINET ANT WHITE FINISH,4,2010-12-02 10:56:00,6.95,17850,United Kingdom
3457,536630,22752,SET 7 BABUSHKA NESTING BOXES,2,2010-12-02 10:56:00,7.65,17850,United Kingdom
3805,536685,22752,SET 7 BABUSHKA NESTING BOXES,4,2010-12-02 12:23:00,7.65,17850,United Kingdom
3806,536685,22803,IVORY EMBROIDERED QUILT,2,2010-12-02 12:23:00,35.75,17850,United Kingdom
3816,536685,82486,WOOD S/3 CABINET ANT WHITE FINISH,4,2010-12-02 12:23:00,6.95,17850,United Kingdom
3831,536690,82486,WOOD S/3 CABINET ANT WHITE FINISH,4,2010-12-02 12:25:00,6.95,17850,United Kingdom
3837,536690,22752,SET 7 BABUSHKA NESTING BOXES,4,2010-12-02 12:25:00,7.65,17850,United Kingdom
3838,536690,22803,IVORY EMBROIDERED QUILT,2,2010-12-02 12:25:00,35.75,17850,United Kingdom
4171,536750,82486,WOOD S/3 CABINET ANT WHITE FINISH,4,2010-12-02 14:04:00,6.95,17850,United Kingdom
4177,536750,22752,SET 7 BABUSHKA NESTING BOXES,4,2010-12-02 14:04:00,7.65,17850,United Kingdom
4178,536750,22803,IVORY EMBROIDERED QUILT,2,2010-12-02 14:04:00,35.75,17850,United Kingdom
4192,536752,82486,WOOD S/3 CABINET ANT WHITE FINISH,4,2010-12-02 14:06:00,6.95,17850,United Kingdom
4198,536752,22752,SET 7 BABUSHKA NESTING BOXES,4,2010-12-02 14:06:00,7.65,17850,United Kingdom
4199,536752,22803,IVORY EMBROIDERED QUILT,2,2010-12-02 14:06:00,35.75,17850,United Kingdom
4521,536787,22752,SET 7 BABUSHKA NESTING BOXES,2,2010-12-02 15:24:00,7.65,17850,United Kingdom
4535,536790,82486,WOOD S/3 CABINET ANT WHITE FINISH,4,2010-12-02 15:26:00,6.95,17850,United Kingdom
4540,536790,22752,SET 7 BABUSHKA NESTING BOXES,4,2010-12-02 15:26:00,7.65,17850,United Kingdom
4541,536790,22803,IVORY EMBROIDERED QUILT,3,2010-12-02 15:26:00,35.75,17850,United Kingdom

In [25]:
# SELECT * FROM retial WHERE CustomerID='17850' or Country ='France';
retail[(retail.CustomerID == '17850') | (retail.Country == 'France')]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom
...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680,France

In [26]:
#select * from retail where InvoiceNo is not null;
retail[retail.InvoiceNo.notnull()]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom
...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680,France

In [27]:
retail[retail.InvoiceNo.isnull()]

Empty DataFrame
Columns: [InvoiceNo, StockCode, Description, Quantity, InvoiceDate, UnitPrice, CustomerID, Country]
Index: []

####Grupowanie